import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Operational Minimalism — exact tokens from stitch design system
        "background": "#0c141d",
        "surface": "#151D2A",
        "surface-elevated": "#1C2635",
        "surface-container": "#18202a",
        "surface-container-low": "#141c25",
        "surface-container-high": "#232b34",
        "surface-container-highest": "#2d353f",
        "surface-container-lowest": "#070f18",
        "surface-dim": "#0c141d",
        "surface-bright": "#323a44",
        "surface-variant": "#2d353f",
        "surface-tint": "#50dbcb",
        "border-muted": "#2B3648",
        "on-surface": "#dbe3f0",
        "on-surface-variant": "#bbcac6",
        "on-background": "#dbe3f0",
        "inverse-surface": "#dbe3f0",
        "inverse-on-surface": "#29313b",
        "outline": "#859491",
        "outline-variant": "#3c4947",
        "text-primary": "#E8EEF7",
        "text-secondary": "#94A3B8",
        "primary": "#50dbcb",
        "on-primary": "#003732",
        "primary-container": "#00b3a4",
        "on-primary-container": "#003e38",
        "primary-fixed": "#71f8e7",
        "primary-fixed-dim": "#50dbcb",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#005049",
        "inverse-primary": "#006a61",
        "secondary": "#b8c3ff",
        "on-secondary": "#002388",
        "secondary-container": "#0736ba",
        "on-secondary-container": "#a1b1ff",
        "secondary-fixed": "#dde1ff",
        "secondary-fixed-dim": "#b8c3ff",
        "on-secondary-fixed": "#001355",
        "on-secondary-fixed-variant": "#0736ba",
        "tertiary": "#ffba3e",
        "on-tertiary": "#432c00",
        "tertiary-container": "#d49300",
        "on-tertiary-container": "#4b3200",
        "tertiary-fixed": "#ffdeae",
        "tertiary-fixed-dim": "#ffba3e",
        "on-tertiary-fixed": "#281900",
        "on-tertiary-fixed-variant": "#604100",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "critical": "#D64545",
      },
      borderRadius: {
        DEFAULT: "0.125rem", // 2px — sharp, enterprise
        lg: "0.25rem",       // 4px
        xl: "0.5rem",        // 8px
        full: "9999px",
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "12px",
        "lg": "16px",
        "xl": "24px",
        "xxl": "32px",
        "gutter": "16px",
        "sidebar-width": "240px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "display-lg": ["Satoshi", "sans-serif"],
        "stat-lg": ["Satoshi", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "body-bold": ["Inter", "sans-serif"],
        "label-caps": ["Geist Mono", "monospace"],
        "mono-technical": ["Geist Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "stat-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-bold": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "mono-technical": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      gridTemplateColumns: {
        "24": "repeat(24, minmax(0, 1fr))",
      },
    },
  },
  plugins: [],
};

export default config;
