import prisma from "@/lib/db";
import { z } from "zod";
import { NextResponse } from "next/server";
import {
  generateGuardrailYaml,
  hashGuardrailYaml,
  guardrailFilePath,
} from "@/lib/guardrails/generator";
import { GitHubConnector } from "@/lib/connectors/github";
import { GitLabConnector } from "@/lib/connectors/gitlab";
import { JiraConnector } from "@/lib/connectors/jira";
import { GovernanceEventType } from "@prisma/client";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

const PushSchema = z.object({
  projectId: z.string(),
  connectorId: z.string(),
  boardId: z.string().min(1),             // "owner/repo" for GitHub, "namespace/project" for GitLab
  framework: z.string(),
  defaultBranch: z.string().optional().default("main"),
  jiraConnectorId: z.string().optional(), // if set, creates a Jira Story after PR
});

export async function POST(req: Request) {
  const body = await req.json();
  const parsed = PushSchema.safeParse(body);
  if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });

  const { projectId, connectorId, boardId, framework, defaultBranch, jiraConnectorId } =
    parsed.data;

  const [project, connector] = await Promise.all([
    prisma.project.findUnique({ where: { id: projectId }, select: { key: true, name: true } }),
    prisma.sourceConnector.findUnique({ where: { id: connectorId } }),
  ]);

  if (!project) return NextResponse.json({ error: "Project not found" }, { status: 404 });
  if (!connector) return NextResponse.json({ error: "Connector not found" }, { status: 404 });

  const yaml = generateGuardrailYaml({ projectKey: project.key, projectName: project.name, framework });
  const rulesHash = hashGuardrailYaml(yaml);
  const repoPath = guardrailFilePath(framework);

  const existing = await prisma.guardrailPush.findFirst({
    where: { projectId, framework, rulesHash, status: { in: ["PENDING", "MERGED"] } },
  });
  if (existing) return NextResponse.json({ alreadyExists: true, push: existing });

  const creds = connector.credentials as Record<string, string>;
  const token = creds.token ?? creds.apiToken ?? "";
  let prUrl: string | null = null;
  let prNumber: number | null = null;
  let status = "PENDING";

  try {
    const prBody = `NexoriOS is pushing governance guardrails for the **${framework}** framework.\n\nThis file defines required governance gates, data handling requirements, and AI guardrails enforced by NexoriOS.\n\n**Project:** ${project.name} (${project.key})\n**Framework:** ${framework}\n**Repo:** ${boardId}\n\n> Do not edit this file manually — regenerate via NexoriOS → Assurance Intelligence.`;

    if (connector.type === "github") {
      const [owner, repo] = boardId.split("/");
      const gh = new GitHubConnector({ token, owner, repo });
      const pr = await gh.createPullRequest!({
        title: `[GOVERNANCE] Add ${framework} guardrails for ${project.name}`,
        body: prBody,
        filePath: repoPath,
        fileContent: yaml,
        baseBranch: defaultBranch,
      });
      prUrl = pr.url ?? null;
      prNumber = pr.number ?? null;
    } else if (connector.type === "gitlab") {
      const gl = new GitLabConnector({ token, baseUrl: connector.baseUrl, projectId: boardId });
      const pr = await gl.createPullRequest!({
        title: `[GOVERNANCE] Add ${framework} guardrails for ${project.name}`,
        body: prBody,
        filePath: repoPath,
        fileContent: yaml,
        baseBranch: defaultBranch,
      });
      prUrl = pr.url ?? null;
      prNumber = pr.number ?? null;
    }
  } catch (err) {
    status = "FAILED";
    console.error("Guardrail push failed:", err);
  }

  const push = await prisma.$transaction(async (tx) => {
    const p = await tx.guardrailPush.create({
      data: { projectId, connectorId, framework, repoPath, prUrl, prNumber, rulesHash, status },
    });
    await tx.governanceEvent.create({
      data: {
        projectId,
        type: GovernanceEventType.GUARDRAIL_PUSHED,
        resourceType: "GuardrailPush",
        resourceId: p.id,
        payload: { framework, repoPath, prUrl, prNumber, status, rulesHash, boardId },
      },
    });
    return p;
  });

  // Create Jira Story if requested and PR succeeded
  let jiraStoryKey: string | null = null;
  if (jiraConnectorId && status !== "FAILED" && prUrl) {
    try {
      const jiraConn = await prisma.sourceConnector.findUnique({ where: { id: jiraConnectorId } });
      if (jiraConn) {
        const jiraCreds = jiraConn.credentials as Record<string, string>;
        const jira = new JiraConnector(
          jiraConn.baseUrl,
          { email: jiraCreds.email ?? "", apiToken: jiraCreds.apiToken ?? "" },
          {},
          jiraConn.projectKeys[0],
        );
        jiraStoryKey = await jira.createStory({
          title: `[GOV] Add ${framework} guardrails to ${boardId}`,
          description: `NexoriOS has opened a PR to add ${framework} governance guardrails.\n\nPR: ${prUrl}\nRepository: ${boardId}\nProject: ${project.name} (${project.key})\n\nReview and merge the PR to activate the governance rules in your repository.`,
          labels: ["nexori-governance", framework.toLowerCase().replace(/_/g, "-")],
        });
      }
    } catch {
      // Non-fatal — PR was still created successfully
    }
  }

  return NextResponse.json(
    { ...push, jiraStoryKey },
    { status: status === "FAILED" ? 500 : 201 },
  );
}
