import prisma from "@/lib/db";
import { z } from "zod";
import { NextResponse } from "next/server";
import {
  generateGuardrailYaml,
  hashGuardrailYaml,
  guardrailFilePath,
} from "@/lib/guardrails/generator";
import { getConnector } from "@/lib/connectors";
import { GovernanceEventType } from "@prisma/client";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

const PushSchema = z.object({
  projectId: z.string(),
  connectorId: z.string(),
  framework: z.string(),
  defaultBranch: z.string().optional().default("main"),
});

export async function POST(req: Request) {
  const body = await req.json();
  const parsed = PushSchema.safeParse(body);
  if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });

  const { projectId, connectorId, framework, defaultBranch } = parsed.data;

  const [project, connector] = await Promise.all([
    prisma.project.findUnique({ where: { id: projectId }, select: { key: true, name: true } }),
    prisma.sourceConnector.findUnique({ where: { id: connectorId } }),
  ]);

  if (!project) return NextResponse.json({ error: "Project not found" }, { status: 404 });
  if (!connector) return NextResponse.json({ error: "Connector not found" }, { status: 404 });

  const yaml = generateGuardrailYaml({
    projectKey: project.key,
    projectName: project.name,
    framework,
  });
  const rulesHash = hashGuardrailYaml(yaml);
  const repoPath = guardrailFilePath(framework);

  // Check if already pushed with same hash
  const existing = await prisma.guardrailPush.findFirst({
    where: { projectId, framework, rulesHash, status: { in: ["PENDING", "MERGED"] } },
  });
  if (existing) {
    return NextResponse.json({ alreadyExists: true, push: existing });
  }

  let prUrl: string | null = null;
  let prNumber: number | null = null;
  let status = "PENDING";

  try {
    const conn = getConnector(connector);
    if (conn.createPullRequest) {
      const pr = await conn.createPullRequest({
        title: `[GOVERNANCE] Add ${framework} guardrails for ${project.name}`,
        body: `NexoriOS is pushing governance guardrails for the **${framework}** framework.\n\nThis file defines required governance gates, data handling requirements, and AI guardrails enforced by NexoriOS.\n\n**Project:** ${project.name} (${project.key})\n**Framework:** ${framework}\n\n---\nDo not edit this file manually — regenerate via NexoriOS Admin → Compliance Intelligence.`,
        filePath: repoPath,
        fileContent: yaml,
        baseBranch: defaultBranch,
      });
      prUrl = pr.url ?? null;
      prNumber = pr.number ?? null;
    }
  } catch (err) {
    status = "FAILED";
    console.error("Guardrail push failed:", err);
  }

  const push = await prisma.$transaction(async (tx) => {
    const p = await tx.guardrailPush.create({
      data: { projectId, connectorId, framework, repoPath, prUrl, prNumber, rulesHash, status },
    });
    await tx.governanceEvent.create({
      data: {
        projectId,
        type: GovernanceEventType.GUARDRAIL_PUSHED,
        resourceType: "GuardrailPush",
        resourceId: p.id,
        payload: { framework, repoPath, prUrl, prNumber, status, rulesHash },
      },
    });
    return p;
  });

  return NextResponse.json(push, { status: status === "FAILED" ? 500 : 201 });
}
