import { createHash } from "crypto";

export interface GuardrailConfig {
  projectKey: string;
  projectName: string;
  framework: string;
  caseId?: string;
  generatedAt?: string;
}

const FRAMEWORK_RULES: Record<
  string,
  {
    gatesRequired: string[];
    dataHandling?: Record<string, string>;
    aiGuardrails?: Record<string, string>;
    exceptionTracking?: Record<string, string>;
  }
> = {
  GDPR: {
    gatesRequired: ["dpo-review", "data-processing-assessment", "privacy-by-design-check"],
    dataHandling: {
      personal_data_labeling: "required",
      encryption_at_rest: "required",
      retention_policy: "required",
      cross_border_transfer: "review_required",
    },
    aiGuardrails: {
      prompt_injection_check: "enforced",
      output_filtering: "pii_redacted",
      model_logging: "required",
      human_in_loop: "required_for_decisions",
    },
    exceptionTracking: {
      platform_waivers: "required",
      tool_story: "required",
    },
  },
  DORA: {
    gatesRequired: [
      "ict-risk-assessment",
      "resilience-review",
      "dora-article28-check",
      "incident-response-check",
    ],
    dataHandling: {
      ict_asset_classification: "required",
      backup_validation: "required",
      rto_rpo_documented: "required",
    },
    aiGuardrails: {
      third_party_ai_review: "required",
      model_substitution_plan: "required",
    },
    exceptionTracking: {
      platform_waivers: "required",
      tool_story: "required",
    },
  },
  SOC2: {
    gatesRequired: [
      "security-review",
      "access-control-review",
      "monitoring-validation",
      "change-management-sign-off",
    ],
    dataHandling: {
      data_encryption: "required",
      access_logging: "required",
      least_privilege: "enforced",
    },
    aiGuardrails: {
      output_audit_logging: "required",
      model_access_control: "enforced",
    },
    exceptionTracking: {
      platform_waivers: "required",
      tool_story: "required",
    },
  },
  EU_AI_ACT: {
    gatesRequired: [
      "ai-risk-assessment",
      "ai-ethics-review",
      "human-override-validation",
      "bias-assessment",
      "transparency-check",
    ],
    aiGuardrails: {
      prohibited_use_check: "enforced",
      high_risk_classification: "required",
      human_oversight: "mandatory",
      conformity_assessment: "required",
      technical_documentation: "required",
    },
    exceptionTracking: {
      platform_waivers: "required",
      tool_story: "required",
      regulator_notification: "if_high_risk",
    },
  },
  ISO_27001: {
    gatesRequired: [
      "isms-review",
      "risk-treatment-sign-off",
      "security-review",
      "supplier-security-review",
    ],
    dataHandling: {
      information_classification: "required",
      cryptography_policy: "required",
      physical_security: "documented",
    },
    aiGuardrails: {
      ai_asset_inventory: "required",
      model_risk_treatment: "required",
    },
    exceptionTracking: {
      platform_waivers: "required",
      tool_story: "required",
    },
  },
};

function yamlValue(v: string): string {
  return v.includes(" ") ? `"${v}"` : v;
}

function objToYaml(obj: Record<string, string>, indent: number): string {
  const pad = " ".repeat(indent);
  return Object.entries(obj)
    .map(([k, v]) => `${pad}${k}: ${yamlValue(v)}`)
    .join("\n");
}

export function generateGuardrailYaml(config: GuardrailConfig): string {
  const rules = FRAMEWORK_RULES[config.framework];
  if (!rules) throw new Error(`Unknown framework: ${config.framework}`);

  const now = config.generatedAt ?? new Date().toISOString();
  const lines: string[] = [
    `# .github/governance/${config.framework.toLowerCase()}-rules.yaml`,
    `# Generated by NexoriOS — do not edit manually`,
    `framework: ${config.framework}`,
    `version: "1.0"`,
    `enforced_by: NexoriOS`,
    `project: ${config.projectKey}`,
    `generated_at: ${now}`,
  ];

  if (config.caseId) lines.push(`nexori_case_id: ${config.caseId}`);

  lines.push("", "gates_required:");
  for (const gate of rules.gatesRequired) {
    lines.push(`  - ${gate}`);
  }

  if (rules.dataHandling) {
    lines.push("", "data_handling:");
    lines.push(objToYaml(rules.dataHandling, 2));
  }

  if (rules.aiGuardrails) {
    lines.push("", "ai_guardrails:");
    lines.push(objToYaml(rules.aiGuardrails, 2));
  }

  if (rules.exceptionTracking) {
    lines.push("", "exception_tracking:");
    lines.push(objToYaml(rules.exceptionTracking, 2));
  }

  return lines.join("\n") + "\n";
}

export function hashGuardrailYaml(yaml: string): string {
  return createHash("sha256").update(yaml).digest("hex");
}

export function guardrailFilePath(framework: string): string {
  return `.github/governance/${framework.toLowerCase().replace(/_/g, "-")}-rules.yaml`;
}
